services:
  - type: web
    name: hacker-x-chatbot
    runtime: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /healthz

    envVars:
      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: SESSION_STRING
        sync: false

      - key: MONGO_URL
        sync: false

      - key: ARC_API_KEY
        sync: false

      - key: PYROGRAM_REQUEST_TIMEOUT
        value: "60"

      - key: MUSIC_DOWNLOAD_TIMEOUT
        value: "90"

      - key: MUSIC_COMMAND_TIMEOUT
        value: "360"

      - key: DATABASE_NAME
        value: AlexaDb

      - key: REPLY_DELAY
        value: "0"

      - key: REPLY_TO_NORMAL_MESSAGES
        value: "true"

      - key: MAX_PENDING_JOBS
        value: "1000"

      - key: LOG_LEVEL
        value: INFO

      - key: APP_NAME
        value: VIP-ID-CHATBOT

